import turtle

screen = turtle.Screen()
screen.screensize( 500, 500)
screen.bgcolor("lightblue")

t = turtle.Turtle()
t.speed(0)


# water
t.penup()
t.goto(-5000,50)
t.pendown()
t.fillcolor("dodgerblue4")
t.pencolor("dodgerblue4")
t.begin_fill()
t.goto(5000,50)
t.goto(5000,-150)
t.goto(-5000,-150)
t.goto(-5000,50)
t.hideturtle()
t.end_fill()

# sand
t.penup()
t.goto(-1000,-50)
t.pendown()
t.fillcolor("peachpuff")
t.pencolor("peachpuff")
t.begin_fill()
t.goto(5000,-50)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,-50)
t.hideturtle()
t.end_fill()

# cloud
t.penup()
t.goto(50,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(70)
t.end_fill()

t.penup()
t.goto(120,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(-20,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(-50,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(170,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.hideturtle()
t.end_fill()

# sun
t.penup()
t.goto(-250,200)
t.pendown()
t.fillcolor("gold")
t.pencolor("gold")
t.begin_fill()
t.circle(90)
t.hideturtle()
t.end_fill()

# waves
t.penup()
t.goto(0,-75)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~", font=("Arial", 30, "bold"), align="center")
t.end_fill()

t.penup()
t.goto(0,-55)
t.pendown()
t.fillcolor("lightskyblue")
t.pencolor("lightskyblue")
t.begin_fill()
t.write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~", font=("Arial", 30, "bold"), align="center")
t.end_fill()

t.penup()
t.goto(0,-35)
t.pendown()
t.fillcolor("skyblue")
t.pencolor("skyblue")
t.begin_fill()
t.write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~", font=("Arial", 30, "bold"), align="center")
t.end_fill()

t.penup()
t.goto(0,-15)
t.pendown()
t.fillcolor("dodgerblue2")
t.pencolor("dodgerblue2")
t.begin_fill()
t.write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~", font=("Arial", 30, "bold"), align="center")
t.end_fill()

t.penup()
t.goto(0,10)
t.pendown()
t.fillcolor("dodgerblue3")
t.pencolor("dodgerblue3")
t.begin_fill()
t.write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~", font=("Arial", 30, "bold"), align="center")
t.end_fill()

t.penup()
t.goto(50,290)
t.pendown()
t.fillcolor("azure3")
t.pencolor("azure3")
t.begin_fill()
t.write("Happy Summer", font=("Arial", 20, "bold"), align="center")
t.end_fill()

# beach ball
t.penup()
t.goto(-250,-200)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(20)
t.hideturtle()
t.end_fill()

# towels
t.penup()
t.goto(100, -320)
t.pendown()
t.setheading(8)
t.pencolor("cadetblue2")
t.fillcolor("cadetblue2")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.end_fill()

t.penup()
t.goto(-100, -330)
t.pendown()
t.setheading(5)
t.pencolor("lightsalmon")
t.fillcolor("lightsalmon")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.end_fill()

# umbrella
t.pensize(3)
t.penup()
t.goto(125,-190)
t.setheading(90)
t.pendown()
t.pencolor('lightyellow')
t.fillcolor('khaki')
t.begin_fill()
t.circle(100,180)
t.end_fill()
t.penup()
t.goto(125,-190)
t.setheading(90)
t.fillcolor('lightyellow')
t.pendown()
for i in range(5):
    t.begin_fill()
    t.circle(20,180)
    t.end_fill()
    t.right(180)
t.setheading(90)
t.penup()
t.goto(30, -300)
t.pendown()
t.pencolor('grey')
t.pensize(15)
t.forward(113)

# shark fin
t.penup()
t.pensize(1)
t.goto(-90,50)
t.pendown()
t.pencolor("dodgerblue3")
t.fillcolor("dodgerblue3")
t.begin_fill()
t.goto(-120,70)
t.goto(-120,50)
t.end_fill()

# birds
t.penup()
t.goto(150,200)
t.pendown()
t.fillcolor("black")
t.pencolor("black")
t.begin_fill()
t.circle(30, 50)
t.hideturtle()
t.end_fill()
t.penup()
t.goto(170,200)
t.pendown()
t.fillcolor("black")
t.pencolor("black")
t.begin_fill()
t.circle(30, 50)
t.hideturtle()
t.end_fill()

t.penup()
t.goto(150,150)
t.pendown()
t.fillcolor("black")
t.pencolor("black")
t.begin_fill()
t.circle(30, -50)
t.hideturtle()
t.end_fill()
t.penup()
t.goto(150,150)
t.pendown()
t.fillcolor("black")
t.pencolor("black")
t.begin_fill()
t.circle(30, 50)
t.hideturtle()
t.end_fill()


t.hideturtle()
turtle.done()